# print macro commands on screen
/control/verbose 2
/control/saveHistory

# geometry file, input here
/geometry/source ...geometry.tg

# add physics lists 
/physics_lists/select QGSP_BERT_HP_EMV

# initialize geometry and physics
/run/initialize

# protons from a proton synchotron
/gps/particle proton
/gps/energy 4 GeV
/gps/position -75 0 0 mm
/gps/direction 1 0 0

# visualize geometry and events for debugging -
/vis/geometry/list
/vis/open OGL
/vis/drawVolume
/vis/viewer/set/style surface
/vis/viewer/set/background white ! ! 0
/vis/viewer/set/lineSegmentsPerCircle 50
/vis/viewer/set/viewpointThetaPhi 35 55
/vis/viewer/set/lightsMove cam
/vis/viewer/flush
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

# particle filter - only neutrons and protons need to be visualised
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add neutron

# drawing trajectories with step-points
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/set proton magenta
/vis/modeling/trajectories/drawByParticleID-0/set neutron green

/vis/scene/endOfEventAction accumulate 15

# turn on detailed information about tracking
/tracking/verbose 2

# dump a few events on screen for debugging
/run/beamOn 5

# turn off screen printing for fast simulation 
/vis/disable
/tracking/verbose 0

# turn on data recording
/analysis/setFileName results.root

# turn on progress report
/run/verbose 2
/run/printProgress 1000

# start simulation
/run/beamOn 1000
